=begin
#GMO Aozora Net Bank Open API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'date'

module SwaggerClient
  class TokenRequest
    # 新規発行時はauthorization_code固定。再発行時はrefresh_token固定。
    attr_accessor :grant_type

    # 新規発行時のみ必須 認可エンドポイントにて当社から返却した認可コード  minLength: 1 maxLength: 128 
    attr_accessor :code

    # 再発行時のみ必須 トークンエンドポイント(新規発行)にて当社から返却したリフレッシュトークン。  minLength: 1 maxLength: 128 
    attr_accessor :refresh_token

    # 新規発行時のみ必須 貴社が指定する認可コードをリダイレクトするためのURI。 事前に登録済みのリダイレクトURIであることが必要、それ以外の場合はエラーとする。 ※認可エンドポイント要求時の「redirect_uri」と同じ値。  minLength: 1 maxLength: 256 
    attr_accessor :redirect_uri

    # クライアントID。(貴社認証用の項目) (当社が事前に発行する貴社向けのID) 事前に登録する「クライアント認証方式」にclient_secret_basic(ベーシック認証)を設定した場合、設定不要。 「クライアント認証方式」にclient_secret_post(パラメーター認証)を設定した場合、必須。  minLength: 1 maxLength: 128 
    attr_accessor :client_id

    # クライアントシークレット。(貴社認証用の項目) (当社が事前に発行する貴社向けのID) 事前に登録する「クライアント認証方式」にclient_secret_basic(ベーシック認証)を設定した場合、設定不要。 「クライアント認証方式」にclient_secret_post(パラメーター認証)を設定した場合、必須。  minLength: 1 maxLength: 128 
    attr_accessor :client_secret

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'grant_type' => :'grant_type',
        :'code' => :'code',
        :'refresh_token' => :'refresh_token',
        :'redirect_uri' => :'redirect_uri',
        :'client_id' => :'client_id',
        :'client_secret' => :'client_secret'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'grant_type' => :'String',
        :'code' => :'String',
        :'refresh_token' => :'String',
        :'redirect_uri' => :'String',
        :'client_id' => :'String',
        :'client_secret' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'grant_type')
        self.grant_type = attributes[:'grant_type']
      end

      if attributes.has_key?(:'code')
        self.code = attributes[:'code']
      end

      if attributes.has_key?(:'refresh_token')
        self.refresh_token = attributes[:'refresh_token']
      end

      if attributes.has_key?(:'redirect_uri')
        self.redirect_uri = attributes[:'redirect_uri']
      end

      if attributes.has_key?(:'client_id')
        self.client_id = attributes[:'client_id']
      end

      if attributes.has_key?(:'client_secret')
        self.client_secret = attributes[:'client_secret']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @grant_type.nil?
        invalid_properties.push('invalid value for "grant_type", grant_type cannot be nil.')
      end

      if @code.nil?
        invalid_properties.push('invalid value for "code", code cannot be nil.')
      end

      if @code.to_s.length > 128
        invalid_properties.push('invalid value for "code", the character length must be smaller than or equal to 128.')
      end

      if @code.to_s.length < 1
        invalid_properties.push('invalid value for "code", the character length must be great than or equal to 1.')
      end

      if !@refresh_token.nil? && @refresh_token.to_s.length > 128
        invalid_properties.push('invalid value for "refresh_token", the character length must be smaller than or equal to 128.')
      end

      if !@refresh_token.nil? && @refresh_token.to_s.length < 1
        invalid_properties.push('invalid value for "refresh_token", the character length must be great than or equal to 1.')
      end

      if !@redirect_uri.nil? && @redirect_uri.to_s.length > 256
        invalid_properties.push('invalid value for "redirect_uri", the character length must be smaller than or equal to 256.')
      end

      if !@redirect_uri.nil? && @redirect_uri.to_s.length < 1
        invalid_properties.push('invalid value for "redirect_uri", the character length must be great than or equal to 1.')
      end

      if !@client_id.nil? && @client_id.to_s.length > 128
        invalid_properties.push('invalid value for "client_id", the character length must be smaller than or equal to 128.')
      end

      if !@client_id.nil? && @client_id.to_s.length < 1
        invalid_properties.push('invalid value for "client_id", the character length must be great than or equal to 1.')
      end

      if !@client_secret.nil? && @client_secret.to_s.length > 128
        invalid_properties.push('invalid value for "client_secret", the character length must be smaller than or equal to 128.')
      end

      if !@client_secret.nil? && @client_secret.to_s.length < 1
        invalid_properties.push('invalid value for "client_secret", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @grant_type.nil?
      return false if @code.nil?
      return false if @code.to_s.length > 128
      return false if @code.to_s.length < 1
      return false if !@refresh_token.nil? && @refresh_token.to_s.length > 128
      return false if !@refresh_token.nil? && @refresh_token.to_s.length < 1
      return false if !@redirect_uri.nil? && @redirect_uri.to_s.length > 256
      return false if !@redirect_uri.nil? && @redirect_uri.to_s.length < 1
      return false if !@client_id.nil? && @client_id.to_s.length > 128
      return false if !@client_id.nil? && @client_id.to_s.length < 1
      return false if !@client_secret.nil? && @client_secret.to_s.length > 128
      return false if !@client_secret.nil? && @client_secret.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] code Value to be assigned
    def code=(code)
      if code.nil?
        fail ArgumentError, 'code cannot be nil'
      end

      if code.to_s.length > 128
        fail ArgumentError, 'invalid value for "code", the character length must be smaller than or equal to 128.'
      end

      if code.to_s.length < 1
        fail ArgumentError, 'invalid value for "code", the character length must be great than or equal to 1.'
      end

      @code = code
    end

    # Custom attribute writer method with validation
    # @param [Object] refresh_token Value to be assigned
    def refresh_token=(refresh_token)
      if !refresh_token.nil? && refresh_token.to_s.length > 128
        fail ArgumentError, 'invalid value for "refresh_token", the character length must be smaller than or equal to 128.'
      end

      if !refresh_token.nil? && refresh_token.to_s.length < 1
        fail ArgumentError, 'invalid value for "refresh_token", the character length must be great than or equal to 1.'
      end

      @refresh_token = refresh_token
    end

    # Custom attribute writer method with validation
    # @param [Object] redirect_uri Value to be assigned
    def redirect_uri=(redirect_uri)
      if !redirect_uri.nil? && redirect_uri.to_s.length > 256
        fail ArgumentError, 'invalid value for "redirect_uri", the character length must be smaller than or equal to 256.'
      end

      if !redirect_uri.nil? && redirect_uri.to_s.length < 1
        fail ArgumentError, 'invalid value for "redirect_uri", the character length must be great than or equal to 1.'
      end

      @redirect_uri = redirect_uri
    end

    # Custom attribute writer method with validation
    # @param [Object] client_id Value to be assigned
    def client_id=(client_id)
      if !client_id.nil? && client_id.to_s.length > 128
        fail ArgumentError, 'invalid value for "client_id", the character length must be smaller than or equal to 128.'
      end

      if !client_id.nil? && client_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "client_id", the character length must be great than or equal to 1.'
      end

      @client_id = client_id
    end

    # Custom attribute writer method with validation
    # @param [Object] client_secret Value to be assigned
    def client_secret=(client_secret)
      if !client_secret.nil? && client_secret.to_s.length > 128
        fail ArgumentError, 'invalid value for "client_secret", the character length must be smaller than or equal to 128.'
      end

      if !client_secret.nil? && client_secret.to_s.length < 1
        fail ArgumentError, 'invalid value for "client_secret", the character length must be great than or equal to 1.'
      end

      @client_secret = client_secret
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          grant_type == o.grant_type &&
          code == o.code &&
          refresh_token == o.refresh_token &&
          redirect_uri == o.redirect_uri &&
          client_id == o.client_id &&
          client_secret == o.client_secret
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [grant_type, code, refresh_token, redirect_uri, client_id, client_secret].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
