=begin
#GMO Aozora Net Bank Open API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AuthorizationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthorizationApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AuthorizationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthorizationApi' do
    it 'should create an instance of AuthorizationApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AuthorizationApi)
    end
  end

  # unit tests for authorization
  # 認可
  # クライアントがユーザーの認証・認可を得るためのエンドポイント
  # @param client_id クライアントID (当社が事前に発行する貴社向けのID)  minLength: 1 maxLength: 128 
  # @param redirect_uri 貴社が指定する認可コードをリダイレクトするためのURI  minLength: 1 maxLength: 256 
  # @param response_type 認可フロータイプ。 code固定
  # @param scope 要求されるアクセス権限を示すスコープID。 複数設定する場合は半角スペース区切りにて連結。 リフレッシュトークンを発行する場合は offline_access scope値が必要。  minLength: 1 maxLength: 256 
  # @param state 貴社にて指定。(要求と応答の間で維持されるランダム値) CSRF対策として同一のセッションであることを確認するために利用する項目。  minLength: 1 maxLength: 128 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :nonce Client セッションと ID Token を紐づける文字列。設定された場合はそのままの値をID Tokenに含めて返却する。 リプレイアタック攻撃を防止するため、リクエスト毎にランダム値(十分な不規則性となる値)を設定し ID Tokenに含まれるnonce値が認可エンドポイントリクエスト時と同一であることを一度だけ検証するために利用する項目。  minLength: 1 maxLength: 128 
  # @return [nil]
  describe 'authorization test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
