=begin
#GMO Aozora Net Bank Open API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
## auth
Dir.glob(File.expand_path('../swagger_client/auth/models/*', __FILE__)).each do |file|
  require file
end
## webhooks
Dir.glob(File.expand_path('../swagger_client/webhook/models/*', __FILE__)).each do |file|
  require file
end


# APIs
## auth
require 'swagger_client/auth/api/authorization_api'
require 'swagger_client/auth/api/token_api'
## webhooks
Dir.glob(File.expand_path('../swagger_client/webhook/api/*', __FILE__)).each do |file|
  require file
end


module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default("auth"))
      else
        Configuration.default("auth")
      end
    end
  end
end
