=begin
#GMO Aozora Net Bank Open API

#<p>Ph2.5向けに作成したもの</p> 

OpenAPI spec version: 1.1.10

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'date'

module SwaggerClient
  # 入金口座情報 
  class Account
    # 入金口座ID 半角数字 入金先の口座を識別するID 
    attr_accessor :ra_id

    # 入金口座　支店コード 半角数字 
    attr_accessor :ra_branch_code

    # 半角文字 
    attr_accessor :ra_branch_name_kana

    # 半角数字 
    attr_accessor :ra_account_number

    # 全角文字 
    attr_accessor :ra_holder_name

    # 基準日 半角文字 応答日付、もしくは入金明細の基準日を示す。 YYYY-MM-DD形式 
    attr_accessor :base_date

    # 基準時刻 半角文字 応答時刻、もしくは入金明細の基準時刻を示す。  ISO8601 時差(offset)も表記 HH:MM:SS+09:00形式 
    attr_accessor :base_time

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ra_id' => :'raId',
        :'ra_branch_code' => :'raBranchCode',
        :'ra_branch_name_kana' => :'raBranchNameKana',
        :'ra_account_number' => :'raAccountNumber',
        :'ra_holder_name' => :'raHolderName',
        :'base_date' => :'baseDate',
        :'base_time' => :'baseTime'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'ra_id' => :'String',
        :'ra_branch_code' => :'String',
        :'ra_branch_name_kana' => :'String',
        :'ra_account_number' => :'String',
        :'ra_holder_name' => :'String',
        :'base_date' => :'String',
        :'base_time' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'raId')
        self.ra_id = attributes[:'raId']
      end

      if attributes.has_key?(:'raBranchCode')
        self.ra_branch_code = attributes[:'raBranchCode']
      end

      if attributes.has_key?(:'raBranchNameKana')
        self.ra_branch_name_kana = attributes[:'raBranchNameKana']
      end

      if attributes.has_key?(:'raAccountNumber')
        self.ra_account_number = attributes[:'raAccountNumber']
      end

      if attributes.has_key?(:'raHolderName')
        self.ra_holder_name = attributes[:'raHolderName']
      end

      if attributes.has_key?(:'baseDate')
        self.base_date = attributes[:'baseDate']
      end

      if attributes.has_key?(:'baseTime')
        self.base_time = attributes[:'baseTime']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @ra_id.nil?
        invalid_properties.push('invalid value for "ra_id", ra_id cannot be nil.')
      end

      if @ra_id.to_s.length > 29
        invalid_properties.push('invalid value for "ra_id", the character length must be smaller than or equal to 29.')
      end

      if @ra_id.to_s.length < 12
        invalid_properties.push('invalid value for "ra_id", the character length must be great than or equal to 12.')
      end

      if @ra_branch_code.nil?
        invalid_properties.push('invalid value for "ra_branch_code", ra_branch_code cannot be nil.')
      end

      if @ra_branch_code.to_s.length > 3
        invalid_properties.push('invalid value for "ra_branch_code", the character length must be smaller than or equal to 3.')
      end

      if @ra_branch_code.to_s.length < 3
        invalid_properties.push('invalid value for "ra_branch_code", the character length must be great than or equal to 3.')
      end

      if @ra_branch_name_kana.nil?
        invalid_properties.push('invalid value for "ra_branch_name_kana", ra_branch_name_kana cannot be nil.')
      end

      if @ra_branch_name_kana.to_s.length > 15
        invalid_properties.push('invalid value for "ra_branch_name_kana", the character length must be smaller than or equal to 15.')
      end

      if @ra_branch_name_kana.to_s.length < 1
        invalid_properties.push('invalid value for "ra_branch_name_kana", the character length must be great than or equal to 1.')
      end

      if @ra_account_number.nil?
        invalid_properties.push('invalid value for "ra_account_number", ra_account_number cannot be nil.')
      end

      if @ra_account_number.to_s.length > 7
        invalid_properties.push('invalid value for "ra_account_number", the character length must be smaller than or equal to 7.')
      end

      if @ra_account_number.to_s.length < 7
        invalid_properties.push('invalid value for "ra_account_number", the character length must be great than or equal to 7.')
      end

      if @ra_holder_name.nil?
        invalid_properties.push('invalid value for "ra_holder_name", ra_holder_name cannot be nil.')
      end

      if @ra_holder_name.to_s.length > 48
        invalid_properties.push('invalid value for "ra_holder_name", the character length must be smaller than or equal to 48.')
      end

      if @ra_holder_name.to_s.length < 1
        invalid_properties.push('invalid value for "ra_holder_name", the character length must be great than or equal to 1.')
      end

      if @base_date.nil?
        invalid_properties.push('invalid value for "base_date", base_date cannot be nil.')
      end

      if @base_date.to_s.length > 10
        invalid_properties.push('invalid value for "base_date", the character length must be smaller than or equal to 10.')
      end

      if @base_date.to_s.length < 10
        invalid_properties.push('invalid value for "base_date", the character length must be great than or equal to 10.')
      end

      if @base_time.nil?
        invalid_properties.push('invalid value for "base_time", base_time cannot be nil.')
      end

      if @base_time.to_s.length > 14
        invalid_properties.push('invalid value for "base_time", the character length must be smaller than or equal to 14.')
      end

      if @base_time.to_s.length < 14
        invalid_properties.push('invalid value for "base_time", the character length must be great than or equal to 14.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @ra_id.nil?
      return false if @ra_id.to_s.length > 29
      return false if @ra_id.to_s.length < 12
      return false if @ra_branch_code.nil?
      return false if @ra_branch_code.to_s.length > 3
      return false if @ra_branch_code.to_s.length < 3
      return false if @ra_branch_name_kana.nil?
      return false if @ra_branch_name_kana.to_s.length > 15
      return false if @ra_branch_name_kana.to_s.length < 1
      return false if @ra_account_number.nil?
      return false if @ra_account_number.to_s.length > 7
      return false if @ra_account_number.to_s.length < 7
      return false if @ra_holder_name.nil?
      return false if @ra_holder_name.to_s.length > 48
      return false if @ra_holder_name.to_s.length < 1
      return false if @base_date.nil?
      return false if @base_date.to_s.length > 10
      return false if @base_date.to_s.length < 10
      return false if @base_time.nil?
      return false if @base_time.to_s.length > 14
      return false if @base_time.to_s.length < 14
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] ra_id Value to be assigned
    def ra_id=(ra_id)
      if ra_id.nil?
        fail ArgumentError, 'ra_id cannot be nil'
      end

      if ra_id.to_s.length > 29
        fail ArgumentError, 'invalid value for "ra_id", the character length must be smaller than or equal to 29.'
      end

      if ra_id.to_s.length < 12
        fail ArgumentError, 'invalid value for "ra_id", the character length must be great than or equal to 12.'
      end

      @ra_id = ra_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ra_branch_code Value to be assigned
    def ra_branch_code=(ra_branch_code)
      if ra_branch_code.nil?
        fail ArgumentError, 'ra_branch_code cannot be nil'
      end

      if ra_branch_code.to_s.length > 3
        fail ArgumentError, 'invalid value for "ra_branch_code", the character length must be smaller than or equal to 3.'
      end

      if ra_branch_code.to_s.length < 3
        fail ArgumentError, 'invalid value for "ra_branch_code", the character length must be great than or equal to 3.'
      end

      @ra_branch_code = ra_branch_code
    end

    # Custom attribute writer method with validation
    # @param [Object] ra_branch_name_kana Value to be assigned
    def ra_branch_name_kana=(ra_branch_name_kana)
      if ra_branch_name_kana.nil?
        fail ArgumentError, 'ra_branch_name_kana cannot be nil'
      end

      if ra_branch_name_kana.to_s.length > 15
        fail ArgumentError, 'invalid value for "ra_branch_name_kana", the character length must be smaller than or equal to 15.'
      end

      if ra_branch_name_kana.to_s.length < 1
        fail ArgumentError, 'invalid value for "ra_branch_name_kana", the character length must be great than or equal to 1.'
      end

      @ra_branch_name_kana = ra_branch_name_kana
    end

    # Custom attribute writer method with validation
    # @param [Object] ra_account_number Value to be assigned
    def ra_account_number=(ra_account_number)
      if ra_account_number.nil?
        fail ArgumentError, 'ra_account_number cannot be nil'
      end

      if ra_account_number.to_s.length > 7
        fail ArgumentError, 'invalid value for "ra_account_number", the character length must be smaller than or equal to 7.'
      end

      if ra_account_number.to_s.length < 7
        fail ArgumentError, 'invalid value for "ra_account_number", the character length must be great than or equal to 7.'
      end

      @ra_account_number = ra_account_number
    end

    # Custom attribute writer method with validation
    # @param [Object] ra_holder_name Value to be assigned
    def ra_holder_name=(ra_holder_name)
      if ra_holder_name.nil?
        fail ArgumentError, 'ra_holder_name cannot be nil'
      end

      if ra_holder_name.to_s.length > 48
        fail ArgumentError, 'invalid value for "ra_holder_name", the character length must be smaller than or equal to 48.'
      end

      if ra_holder_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "ra_holder_name", the character length must be great than or equal to 1.'
      end

      @ra_holder_name = ra_holder_name
    end

    # Custom attribute writer method with validation
    # @param [Object] base_date Value to be assigned
    def base_date=(base_date)
      if base_date.nil?
        fail ArgumentError, 'base_date cannot be nil'
      end

      if base_date.to_s.length > 10
        fail ArgumentError, 'invalid value for "base_date", the character length must be smaller than or equal to 10.'
      end

      if base_date.to_s.length < 10
        fail ArgumentError, 'invalid value for "base_date", the character length must be great than or equal to 10.'
      end

      @base_date = base_date
    end

    # Custom attribute writer method with validation
    # @param [Object] base_time Value to be assigned
    def base_time=(base_time)
      if base_time.nil?
        fail ArgumentError, 'base_time cannot be nil'
      end

      if base_time.to_s.length > 14
        fail ArgumentError, 'invalid value for "base_time", the character length must be smaller than or equal to 14.'
      end

      if base_time.to_s.length < 14
        fail ArgumentError, 'invalid value for "base_time", the character length must be great than or equal to 14.'
      end

      @base_time = base_time
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ra_id == o.ra_id &&
          ra_branch_code == o.ra_branch_code &&
          ra_branch_name_kana == o.ra_branch_name_kana &&
          ra_account_number == o.ra_account_number &&
          ra_holder_name == o.ra_holder_name &&
          base_date == o.base_date &&
          base_time == o.base_time
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [ra_id, ra_branch_code, ra_branch_name_kana, ra_account_number, ra_holder_name, base_date, base_time].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
