=begin
#GMO Aozora Net Bank Open API

#<p>Ph2.5向けに作成したもの</p> 

OpenAPI spec version: 1.1.10

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0

=end

require 'date'

module SwaggerClient
  class VaDepositTransactionMessage
    # メッセージID 半角英数字 メッセージを一意に識別するID 
    attr_accessor :message_id

    # イベント生成日時 半角文字 ISO8601 時差(offset)も表記 YYYY-MM-DDTHH:MM:SS+09:00形式 
    attr_accessor :timestamp

    attr_accessor :account

    attr_accessor :va_transaction

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'message_id' => :'messageId',
        :'timestamp' => :'timestamp',
        :'account' => :'account',
        :'va_transaction' => :'vaTransaction'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'message_id' => :'String',
        :'timestamp' => :'String',
        :'account' => :'Account',
        :'va_transaction' => :'VaTransaction'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'messageId')
        self.message_id = attributes[:'messageId']
      end

      if attributes.has_key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      end

      if attributes.has_key?(:'account')
        self.account = attributes[:'account']
      end

      if attributes.has_key?(:'vaTransaction')
        self.va_transaction = attributes[:'vaTransaction']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @message_id.nil?
        invalid_properties.push('invalid value for "message_id", message_id cannot be nil.')
      end

      if @message_id.to_s.length > 19
        invalid_properties.push('invalid value for "message_id", the character length must be smaller than or equal to 19.')
      end

      if @message_id.to_s.length < 19
        invalid_properties.push('invalid value for "message_id", the character length must be great than or equal to 19.')
      end

      if @timestamp.nil?
        invalid_properties.push('invalid value for "timestamp", timestamp cannot be nil.')
      end

      if @timestamp.to_s.length > 25
        invalid_properties.push('invalid value for "timestamp", the character length must be smaller than or equal to 25.')
      end

      if @timestamp.to_s.length < 25
        invalid_properties.push('invalid value for "timestamp", the character length must be great than or equal to 25.')
      end

      if @account.nil?
        invalid_properties.push('invalid value for "account", account cannot be nil.')
      end

      if @va_transaction.nil?
        invalid_properties.push('invalid value for "va_transaction", va_transaction cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @message_id.nil?
      return false if @message_id.to_s.length > 19
      return false if @message_id.to_s.length < 19
      return false if @timestamp.nil?
      return false if @timestamp.to_s.length > 25
      return false if @timestamp.to_s.length < 25
      return false if @account.nil?
      return false if @va_transaction.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] message_id Value to be assigned
    def message_id=(message_id)
      if message_id.nil?
        fail ArgumentError, 'message_id cannot be nil'
      end

      if message_id.to_s.length > 19
        fail ArgumentError, 'invalid value for "message_id", the character length must be smaller than or equal to 19.'
      end

      if message_id.to_s.length < 19
        fail ArgumentError, 'invalid value for "message_id", the character length must be great than or equal to 19.'
      end

      @message_id = message_id
    end

    # Custom attribute writer method with validation
    # @param [Object] timestamp Value to be assigned
    def timestamp=(timestamp)
      if timestamp.nil?
        fail ArgumentError, 'timestamp cannot be nil'
      end

      if timestamp.to_s.length > 25
        fail ArgumentError, 'invalid value for "timestamp", the character length must be smaller than or equal to 25.'
      end

      if timestamp.to_s.length < 25
        fail ArgumentError, 'invalid value for "timestamp", the character length must be great than or equal to 25.'
      end

      @timestamp = timestamp
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          message_id == o.message_id &&
          timestamp == o.timestamp &&
          account == o.account &&
          va_transaction == o.va_transaction
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [message_id, timestamp, account, va_transaction].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
